service: data-layer

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2

  iamRoleStatements:
    - Effect: Allow
      Action: "*"
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutBucketNotification
      Resource:
        - arn:aws:s3:::my-s3-bucket-data-layer/*

functions:
  lambda1:
    handler: handler.lambda1
    events:
      - s3:
          bucket: my-s3-bucket-data-layer
          events:
            - s3:ObjectCreated:*
          rules:
            - prefix: ECOM/EVENTS
          existing: true

resources:
  Resources:
    FirehoseRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: FirehoseRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - firehose.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: root
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action: s3:*
                  Resource:
                    Fn::Sub: arn:aws:s3:::my-s3-bucket-data-layer/*
    KinesisFirehose:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        ExtendedS3DestinationConfiguration:
          BucketARN: arn:aws:s3:::my-s3-bucket-data-layer
          RoleARN:
            Fn::GetAtt: [FirehoseRole, Arn]
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 1
          Prefix: ECOM/EVENTS/
